---
- name: Install aptitude
  apt:
    name: aptitude
    allow_unauthenticated: yes

- name: Install dirmngr
  apt:
    name: dirmngr
    allow_unauthenticated: yes

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    allow_unauthenticated: yes
